### PR TITLE
end-to-end example of UCI Dataset

### PR DESCRIPTION
**Pull request by ashryaagr**
Initial start for the UCI Dataset Airfoil. I will further add code for plotting and scaling the input using ZScoreTransform from ScikitLearn.jl.

### CODE REVIEW

**Comment by tlienart** [comment]
Hello! thanks for this, it's a good start. I would suggest:

1. adding a few rounds of hyperparameter tuning with cross validation
1. adding a comparison with another classifier

yes plots would be very welcome too, thanks :+1:

**Comment by tlienart** [comment]
Readme changes are all fine by me, thanks!

**Comment by ashryaagr** [comment]
@tlienart I have added the comparison of DecisionTreeRegressor with RandomForestRegressor and have performed hyperparameter tuning too. I have made  use of Standardizer and also plotted a heatmap.
Could you please review the same.

**Comment by tlienart** [comment]
Thanks a lot for your contribution @ashryaagr , looks good to me at first glance, I'll do another full depth pass within the next few days. Cheers!

**Comment by tlienart** [comment]
Sorry for the delay, there seems to be a bug in how CSV reads requests like this, the line to recover the data doesn't seem to work anymore.

**Comment by tlienart** [comment]
nvm, it's an issue with CSV, fixed by upgrading.

**Comment by tlienart** [comment]
ok that looks good, I've done a few fixes/changes and added your name at the top (thanks!!) and will merge this.

**Comment by tlienart** [comment]
closing in favour of #51 , thanks!

**Comment by ablaom** [comment]
Thanks for this both @tlienart @ashryaagr ! 💪

**Pull request closed without merging**
