### PR TITLE
Fix small issue with LGBM end to end

### PR DESCRIPTION
**Pull request by yalwan-iqvia**
I noticed that yscale was log when it should have been xscale, so i've just put this small PR to fix that.

### CODE REVIEW

**Comment by tlienart** [comment]
Nice, thanks!

**Comment by yalwan-iqvia** [comment]
I see that the picture is still wrong so it would seem I changed the code in the wrong place? What is the right place to fix this?

**Comment by tlienart** [comment]
right I  hadn't checked where you fixed it; I just did it in the right place, will push soon and it should be live within 15 minutes or so

**Comment by tlienart** [comment]
https://alan-turing-institute.github.io/DataScienceTutorials.jl/end-to-end/boston-lgbm/

**Comment by yalwan-iqvia** [comment]
Great, thank you and sorry!

**Pull request merged**
